const protocolOptions = {
  title:'长期协议验真',
  node:[
    {
      title:'一级经销商',
      list:[
        {value:'企业基本信息数据'},
        {value:'长期协议签订数据'},
      ]
    },
    {
      title:'二级经销商',
      list:[
        {value:'企业基本信息数据'},
        {value:'长期协议签订数据'},
      ]
    },
  ]
};
const orderOptions = {
  title:'销售合同验真',
  node:[
    {
      title:'一级经销商',
      list:[
        {value:'销售合同数据'},
        {value:'合同签订数据'},
      ]
    },
    {
      title:'云图控股',
      list:[
        {value:'企业历史采购数据'},
      ]
    },
  ]
}
const expressOptions = {
  title:'物流发收货验真',
  node:[
    {
      title:'一级经销商',
      list:[
        {value:'企业基本信息数据'},
        {value:'销售合同数据'},
        {value:'进货采购数据'},
      ]
    },
    {
      title:'云图控股',
      list:[
        {value:'厂方销售数据'},
        {value:'物流发货数据'},
      ]
    },
    {
      title:'二级经销商',
      list:[
        {value:'物流收货数据'},
      ]
    },
  ]
}
export {
  protocolOptions,orderOptions,expressOptions
}
